"use strict";
let estaChovendo = false;
estaChovendo = 'true';
let idade = 27;
let altura = 1.75;
const nacionalidade = 'brasileira';
const colegas = ['lucas', 'fernanda'];
const tecnologias = ['html', 'css', 'js'];
const notas = [7, 8, 5, 9];
const lista = ['gian', true, 27];
let idadeAna = 25;
idadeAna = '25 anos';
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
dadosDaApi = 'string';
let curso = 'front-end';
curso = 10;
